Improved the Android app to handle network issues. Refreshed UI design.
bombardier-gif/covid-vaccine-booking pull request #248
Opened 2021-05-21 14:09 UTC by chris-10

1. Improved UI
2. Handle network issues by retrying DB connection every 10 seconds for 3 minutes until new OTP comes
3. Refactoring of code to improve readability
4. Minor changes to status text strings

2021-05-21 14:30 UTC, chris-10 commented
![screenshot_cowin_app](https://user-images.githubusercontent.com/21965826/119153750-246a1400-ba6f-11eb-98d8-e88602d98c8e.jpg)

2021-05-21 14:32 UTC, BumpyKnuckls commented
@ujaiswal FYI

2021-05-21 14:34 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +    private fun onOTPReceived(sender: String, sms: String, time: Long, i: Int, otp: Int) {
nit:  we should rename `i ` method parameter to more readable name

2021-05-21 14:35 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +        if(i==0) Toast.makeText(this, "Sending OTP to $mKvdbUrl from CoWIN: $sender", Toast.LENGTH_LONG).show()
Should we consider moving `Sending OTP to $mKvdbUrl from CoWIN: $sender`  to string resources as well like you have done for other strings?

2021-05-21 14:39 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +                Thread.sleep(10000)
Would this call block the main Android thread and if yes can it lead to ANRs?

2021-05-21 14:42 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +        mRequestQueue.cancelAll(otp)
Sorry haven;t seen the full existing Android code, but what does this line do?

2021-05-21 14:44 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="288dp"
Would this work fine for smaller screen devices?

2021-05-21 14:45 UTC, BumpyKnuckls requested changes
Left some comments

2021-05-21 14:45 UTC, BumpyKnuckls commented
@chris-10 Thanks a lot for doing this :)

2021-05-21 14:46 UTC, chris-10 commented
Thanks @BumpyKnuckls 
Will implement requested changes and get back

2021-05-21 14:56 UTC, chris-10 commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +                Thread.sleep(10000)
I believe the OTP callback creates a new thread and that thread is paused here. I didn't observe any ANRs in my testing. @ujaiswal can verify this.

2021-05-21 14:58 UTC, chris-10 commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +        mRequestQueue.cancelAll(otp)
Redundancy check that cancels any pending outgoing request corresponding to the current OTP (In case the recursive HTTP request didn't go through)

2021-05-21 14:59 UTC, chris-10 commented on src/CoWinOTPRetriever/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="288dp"
Tested on Pixel 4a (5.81 in). Looks fine to me.

2021-05-21 22:07 UTC, chris-10 commented
@BumpyKnuckls Could you take a look at the changes now? I tested a few edge cases on my devices and it's works as expected.

2021-05-22 06:02 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +            //Log.d("Debug", "New OTP is $otp.")
Should this be uncommented or removed?

2021-05-22 06:02 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +                    //Log.d("Debug", "RetryCounter value is $retryCounter. OTP is $otp. Retrying in 10 seconds..")
Should this be uncommented or removed?

2021-05-22 06:07 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +                Thread.sleep(10000)
Got it. I think lets also test it once with a larger value like 30 seconds or something to be double sure that we won't run into ANR.s

2021-05-22 06:08 UTC, chris-10 commented on src/CoWinOTPRetriever/app/src/main/java/com/indiacowin/cowinotpretriever/MainActivity.kt
> +            //Log.d("Debug", "New OTP is $otp.")
Left it there in case anyone needs to do a quick debug. Will remove once approved.

2021-05-22 06:09 UTC, BumpyKnuckls approved these changes
Overall looks good. Lets watch out for any issues with 10 seconds delay/sleeping logic and see if folks report any issues with ANRs/unresponsive UI @chris-10.

2021-05-22 06:16 UTC, merged

2021-05-22 06:21 UTC, shailesh commented
is the latest APK available for this one in the directory?

2021-05-22 06:29 UTC, chris-10 commented
> is the latest APK available for this one in the directory?

Yes

2021-05-22 07:50 UTC, shailesh commented
![Screenshot_20210522-131615__01](https://user-images.githubusercontent.com/9050349/119218960-8161da80-bb00-11eb-984b-46551951f04f.jpg)
![Screenshot_20210522-131607__01](https://user-images.githubusercontent.com/9050349/119218962-832b9e00-bb00-11eb-9f56-205574f91a70.jpg)
![Screenshot_20210522-131618__01](https://user-images.githubusercontent.com/9050349/119218963-83c43480-bb00-11eb-9972-10a207ad3bcf.jpg)

2021-05-22 08:13 UTC, chris-10 commented
Did you click on "Install Anyway"?

2021-05-22 08:18 UTC, shailesh commented
Yes

2021-05-22 08:34 UTC, chris-10 commented
Thanks @shailesh for reporting this. Can't fix this error from my end. Android does not allow app upgrade unless it is signed with the same certificate.
As of now, we need to resort to fresh install (uninstall old version completely) unless @ujaiswal can generate a signed apk with the same cert as before.

2021-05-22 08:37 UTC, shailesh commented
@chris-10 I could install it another way.

1. uninstalled the already installed version
2. Install it again with new apk