Android app - Better actionable error messages
bombardier-gif/covid-vaccine-booking pull request #424
Opened 2021-05-31 18:20 UTC by chris-10

Fixed #419 - Updated app to display definite actionable error messages. Eliminated any possibility of a 'null' error message.

2021-06-01 15:06 UTC, bombardier-gif commented
@BumpyKnuckls FYI

2021-06-01 15:58 UTC, BumpyKnuckls commented on src/CoWinOTPRetriever/app/src/main/res/values/strings.xml
> +    <string name="error_01">Server is not connected to the internet</string>
Can you please make the string variable names more descriptive? error_01 -> error_server_not_connected
error_02 -> device_not_connected,  error_07 -> error_kvdb_unresponsive and so on...

2021-06-01 16:05 UTC, BumpyKnuckls requested changes
Left a comment. Will leave more comments if required

2021-06-01 16:52 UTC, chris-10 commented on src/CoWinOTPRetriever/app/src/main/res/values/strings.xml
> +    <string name="error_01">Server is not connected to the internet</string>
Done

2021-06-02 06:39 UTC, BumpyKnuckls commented
Thanks @chris-10 for doing this. Landing this one.

2021-06-02 06:40 UTC, merged