Re cycle IP Address
bombardier-gif/covid-vaccine-booking pull request #440
Opened 2021-06-02 11:21 UTC by 6mxo89sqh

### This is POC/Education purpose. Use at your own risk.

Recycle IP Address to get more api call limit

Read the setup notes in [docs/AWS.md](https://github.com/6mxo89sqh/covid-vaccine-booking/blob/rate-limit-ip-restrictions/docs/AWS.md)

Please test and let me know your feedback.

2021-06-02 13:00 UTC, bombardier-gif commented
Thanks @6mxo89sqh Do you think we are good to merge this to master?

2021-06-02 13:07 UTC, 6mxo89sqh commented
@bombardier-gif, i have tested it from my side. but lets wait for atleast one to test this. It should be okay to merge as it doesn't disturb the non AWS users. But, i ll still prefer if we wait for someone to test it.

2021-06-02 17:47 UTC, 6mxo89sqh commented
@shivaslifzz As you are using AWS, can you please test this branch?

2021-06-02 18:01 UTC, shivaslifzz commented
@6mxo89sqh  I tested this code in AWS EC2(UBUNTU) instance with 2nd search option with refresh rate of 3 seconds I am getting the issue related to rate limit 

![image](https://user-images.githubusercontent.com/61616987/120529859-8117e800-c3fa-11eb-961e-46be582de769.png)

![image](https://user-images.githubusercontent.com/61616987/120529990-a278d400-c3fa-11eb-9138-3716b347af96.png)

2021-06-02 18:06 UTC, 6mxo89sqh commented
@shivaslifzz from your logs, I see that you haven't specified aws region. 

Please run the following command before running the script:
`export AWS_DEFAULT_REGION=ap-south-1`

I hope you have configure authentication as mentioned in doc.

2021-06-02 18:23 UTC, shivaslifzz commented
> @shivaslifzz from your logs, I see that you haven't specified aws region.
> 
> Please run the following command before running the script:
> `export AWS_DEFAULT_REGION=ap-south-1`
> 
> I hope you have configure authentication as mentioned in doc.

ENI is chargeable bro

2021-06-02 19:08 UTC, 6mxo89sqh commented
@shivaslifzz One EIP per ec2 instance isn't charged. Refer [here](https://aws.amazon.com/ec2/pricing/on-demand/). Assigning EIP for second ENI is not mandatory. If you assign EIP, you can directly login using to that box. Otherwise, you can ssh from another running machine in same network on private ip of secondary interface.

2021-06-02 19:18 UTC, shivaslifzz commented
> @shivaslifzz One EIP per ec2 instance isn't charged. Refer [here](https://aws.amazon.com/ec2/pricing/on-demand/). Assigning EIP for second ENI is not mandatory. If you assign EIP, you can directly login using to that box. Otherwise, you can ssh from another running machine in same network on private ip of secondary interface.



> @shivaslifzz One EIP per ec2 instance isn't charged. Refer [here](https://aws.amazon.com/ec2/pricing/on-demand/). Assigning EIP for second ENI is not mandatory. If you assign EIP, you can directly login using to that box. Otherwise, you can ssh from another running machine in same network on private ip of secondary interface.

I tried it bro but no luck 

I followed below steps 
1) Created json file in IAM policy
2) Created Elastic Ip and attached it to EC2 instance
3) And connected to the Ec2 instance using EIP only but still getting rate limit issue

2021-06-02 19:29 UTC, 6mxo89sqh commented
@shivaslifzz did you attach the policy to the instance? can you please share logs? (You can [connect with me](https://discord.gg/394ZXQeW) to debug.)

2021-06-02 19:31 UTC, shivaslifzz commented
> @shivaslifzz did you attach the policy to the instance? can you please share logs? (You can [connect with me](https://discord.gg/394ZXQeW) to debug.)

At what time

2021-06-02 19:34 UTC, 6mxo89sqh commented
@shivaslifzz I am online right now.

2021-06-02 19:38 UTC, shivaslifzz commented
> @shivaslifzz I am online right now.

Lets meet now

2021-06-02 19:40 UTC, 6mxo89sqh commented
@shivaslifzz , [here](https://discord.gg/394ZXQeW).

2021-06-02 20:27 UTC, shivaslifzz commented
> @shivaslifzz did you attach the policy to the instance? can you please share logs?

@6mxo89sqh thanks man it's working fine after adding the iam role

2021-06-03 09:37 UTC, bombardier-gif commented
@6mxo89sqh can you resolve the conflicts please, if it doesnt break non aws users, then i will merge this

2021-06-03 10:28 UTC, 6mxo89sqh commented
> @6mxo89sqh can you resolve the conflicts please, if it doesnt break non aws users, then i will merge this

@bombardier-gif done!

2021-06-03 13:16 UTC, ketan commented
Can confirm this works, however instructions are a bit unclear, so I got kicked out even though I was using the secondary IP. It's probably best if we're able to pass all information (including the kvdb key) over CLI, then we can just leave the docker  container running as a daemon.

2021-06-03 18:02 UTC, 6mxo89sqh commented
> Can confirm this works, however instructions are a bit unclear, so I got kicked out even though I was using the secondary IP. It's probably best if we're able to pass all information (including the kvdb key) over CLI, then we can just leave the docker container running as a daemon.

Yes @ketan you can pass all info via cli and run it as daemon. Thats there in readme. 
for kvdb, u need to put `export KVDB_BUCKET=ur key` before you start the script. once the json is generated, you can run it as docker daemon (`--no-tty` flag to docker) :) 

I will add the doc on how to assign secondary EIP. Thanks for the feedback.

2021-06-03 19:20 UTC, 6mxo89sqh commented
@ketan updated the doc.

@bombardier-gif Good to merge. Few users have tried it.

2021-06-03 19:31 UTC, shailesh reviewed
LGTM, let me test this today sometime
 I'll leave a comment if any

2021-06-03 22:54 UTC, AnjunaBoy commented
Hi @6mxo89sqh @shailesh : a question from a noob here. So the changes being tested to cycle the IP, that feature can only be used by some one using AWS? Or will someone like me using Python also be able to use the feature? 

I have no knowledge of AWS EC2 but happy to learn in order to help folks around me. Am i right in assuming that if I dont use AWS, I cannot cycle my IP and will be rate limited after every 20 calendar searches?

2021-06-04 02:21 UTC, shivaslifzz commented
> Hi @6mxo89sqh @shailesh : a question from a noob here. So the changes being tested to cycle the IP, that feature can only be used by some one using AWS? Or will someone like me using Python also be able to use the feature?
> 
> I have no knowledge of AWS EC2 but happy to learn in order to help folks around me. Am i right in assuming that if I dont use AWS, I cannot cycle my IP and will be rate limited after every 20 calendar searches?

You don't need aws you can follow the same old approach it will work

2021-06-04 06:02 UTC, 6mxo89sqh commented
> Hi @6mxo89sqh @shailesh : a question from a noob here. So the changes being tested to cycle the IP, that feature can only be used by some one using AWS? Or will someone like me using Python also be able to use the feature?
> 
> I have no knowledge of AWS EC2 but happy to learn in order to help folks around me. Am i right in assuming that if I dont use AWS, I cannot cycle my IP and will be rate limited after every 20 calendar searches?

Please wait for PRs to be merged.

2021-06-04 06:17 UTC, Nakul93 requested changes

2021-06-04 06:17 UTC, Nakul93 commented on docs/AWS.md
> +3. Create IAM Role by following [this guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#create-iam-role). For step number 4, of AWS guide, use the IAM Policy na
Could you explain these steps in a much more clearer way. In step2 it says you need to paste the json for step no5 which is misleading

2021-06-04 06:27 UTC, 6mxo89sqh commented on docs/AWS.md
> +3. Create IAM Role by following [this guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#create-iam-role). For step number 4, of AWS guide, use the IAM Policy na
Done. Basically, it provides what to paste while following the aws guide.

2021-06-04 06:35 UTC, Nakul93 approved these changes

2021-06-04 06:39 UTC, 6mxo89sqh commented
@bombardier-gif / @shailesh / @Nakul93 Should we merge this?

2021-06-04 06:51 UTC, AnjunaBoy commented
> > Hi @6mxo89sqh @shailesh : a question from a noob here. So the changes being tested to cycle the IP, that feature can only be used by some one using AWS? Or will someone like me using Python also be able to use the feature?
> 
> > 
> 
> > I have no knowledge of AWS EC2 but happy to learn in order to help folks around me. Am i right in assuming that if I dont use AWS, I cannot cycle my IP and will be rate limited after every 20 calendar searches?
> 
> 
> 
> You don't need aws you can follow the same old approach it will work

Thanks for confirming. Looking forward to the merge.

2021-06-04 11:46 UTC, merged