Added Appointment Slip Download Functionality
bombardier-gif/covid-vaccine-booking pull request #472
Opened 2021-06-05 14:13 UTC by dhhruv

Testing Needed...

2021-06-05 15:07 UTC, dhhruv commented
In response to #385 .

2021-06-05 15:16 UTC, bombardier-gif commented
Neat ! let us test this out for a while.

2021-06-05 17:19 UTC, Nakul93 commented
@dhhruv So I've tried out this PR but it didn't download the PDF file. Does it try to store it in the main directory?

2021-06-05 17:22 UTC, Nakul93 commented on src/utils.py
> +
Could you add a print statement for debug purposes and to let the user know that if the PDF was downloaded or not

2021-06-05 17:22 UTC, Nakul93 commented on src/utils.py
> +
Put a print stmt here as well

2021-06-05 18:41 UTC, dhhruv commented
> @dhhruv So I've tried out this PR but it didn't download the PDF file. Does it try to store it in the main directory?

It should download in the current working directory.

2021-06-05 18:42 UTC, shailesh requested changes

2021-06-05 18:42 UTC, shailesh commented on src/utils.py
> +
```
if os.path.exists(f"{resp.json()['appointment_id']}.pdf"):
    print("\nDownload Successful. Check the Current Working Directory for the Appointment Slip.")
else:
    print("\nAppointment Slip Download Failed...")
```

2021-06-05 18:42 UTC, shailesh commented on src/utils.py
> +
Als add a check for status 200/400 
Would be better to Name file as : [**mobile_no__appoint_slip_appointment_id**]

2021-06-05 18:43 UTC, dhhruv commented
```
try:
        appSlipBase = (
            APPOINTMENT_SLIP_URL
            + f"&appointment_id={resp.json()['appointment_confirmation_no']}"
        )
        appslip = requests.get(appSlipBase, headers=request_header)
        with open(
            f"{resp.json()['appointment_confirmation_no']}.pdf", "wb"
        ) as appSlipPdf:
            appSlipPdf.write(appslip.content)
        if os.path.exists(
            f"{resp.json()['appointment_confirmation_no']}.pdf"
        ):
            print(
                "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
            )
        else:
            print(f"{Fore.RED}", end="")
            print("\nAppointment Slip Download Failed...")
        
        except Exception as e:
        print(f"{Fore.RED}", end="")
        print(str(e))
        print(f"{Fore.RESET}", end="")
        print("\n\n")
        beep(WARNING_BEEP_DURATION[0], WARNING_BEEP_DURATION[1])
```
@Nakul93 Try this one. Currently I don't have any open accounts to check, but this must work and I've added changes you asked.

2021-06-05 18:49 UTC, Nakul93 commented on src/utils.py
> +
+1 @shailesh. Having the file name as mobile_no.pdf will make more sense.

2021-06-05 19:04 UTC, Nakul93 commented
@dhhruv Got this error while opening the pdf file
![image](https://user-images.githubusercontent.com/24492930/120902608-e5d37c80-c65e-11eb-8c71-264eddf3ae82.png)

2021-06-05 19:48 UTC, dhhruv commented
> @dhhruv Got this error while opening the pdf file
> ![image](https://user-images.githubusercontent.com/24492930/120902608-e5d37c80-c65e-11eb-8c71-264eddf3ae82.png)

Can you decode and print the incoming data so that we can know what's actually coming through @Nakul93 ?

2021-06-05 20:14 UTC, Nakul93 commented
> > @dhhruv Got this error while opening the pdf file
> > ![image](https://user-images.githubusercontent.com/24492930/120902608-e5d37c80-c65e-11eb-8c71-264eddf3ae82.png)
> 
> Can you decode and print the incoming data so that we can know what's actually coming through @Nakul93 ?

How to do that?

2021-06-05 20:21 UTC, dhhruv commented
```
try:
                    appSlipBase = (
                        APPOINTMENT_SLIP_URL
                        + f"?appointment_id={resp.json()['appointment_confirmation_no']}"
                    )
                    appslip = requests.get(appSlipBase, headers=request_header)
                    with open(
                        f"{resp.json()['appointment_confirmation_no']}.pdf", "wb"
                    ) as appSlipPdf:
                        appSlipPdf.write(appslip.content)
                    if os.path.exists(
                        f"{resp.json()['appointment_confirmation_no']}.pdf"
                    ):
                        print(
                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
                        )
                    else:
                        print("\nAppointment Slip Download Failed...")

                except Exception as e:
                    print(str(e))
                    print("\n\n")
```
**OR**
```
try:
                    appSlipBase = (
                        APPOINTMENT_SLIP_URL
                        + f"?appointment_id={resp.json()['appointment_id']}"
                    )
                    appslip = requests.get(appSlipBase, headers=request_header)
                    with open(
                        f"{resp.json()['appointment_id']}.pdf", "wb"
                    ) as appSlipPdf:
                        appSlipPdf.write(appslip.content)
                    if os.path.exists(
                        f"{resp.json()['appointment_id']}.pdf"
                    ):
                        print(
                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
                        )
                    else:
                        print("\nAppointment Slip Download Failed...")

                except Exception as e:
                    print(str(e))
                    print("\n\n")
```
There was a minor mistake, I've taken care of that. But there's a bit of a confusion as in the Protected API (CoWIN) sends appointment id in json as `appointment_id` but in real it is sending as `appointment_confirmation_no` so I've written 2 code snippets and one of them should definitely work. Can you please take a look @Nakul93 @shailesh and check/test which one is working?

2021-06-05 20:22 UTC, dhhruv commented
> > > @dhhruv Got this error while opening the pdf file
> > > ![image](https://user-images.githubusercontent.com/24492930/120902608-e5d37c80-c65e-11eb-8c71-264eddf3ae82.png)
> > 
> > 
> > Can you decode and print the incoming data so that we can know what's actually coming through @Nakul93 ?
> 
> How to do that?

No needs, the error is solved and any one of the two code snippets shared above will work. Please test and give feedback.

2021-06-05 20:32 UTC, Nakul93 commented
> ```
> try:
>                     appSlipBase = (
>                         APPOINTMENT_SLIP_URL
>                         + f"?appointment_id={resp.json()['appointment_confirmation_no']}"
>                     )
>                     appslip = requests.get(appSlipBase, headers=request_header)
>                     with open(
>                         f"{resp.json()['appointment_confirmation_no']}.pdf", "wb"
>                     ) as appSlipPdf:
>                         appSlipPdf.write(appslip.content)
>                     if os.path.exists(
>                         f"{resp.json()['appointment_confirmation_no']}.pdf"
>                     ):
>                         print(
>                             "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
>                         )
>                     else:
>                         print("\nAppointment Slip Download Failed...")
> 
>                 except Exception as e:
>                     print(str(e))
>                     print("\n\n")
> ```
> 

This is same as before right?

> **OR**
> 
> ```
> try:
>                     appSlipBase = (
>                         APPOINTMENT_SLIP_URL
>                         + f"?appointment_id={resp.json()['appointment_id']}"
>                     )
>                     appslip = requests.get(appSlipBase, headers=request_header)
>                     with open(
>                         f"{resp.json()['appointment_id']}.pdf", "wb"
>                     ) as appSlipPdf:
>                         appSlipPdf.write(appslip.content)
>                     if os.path.exists(
>                         f"{resp.json()['appointment_id']}.pdf"
>                     ):
>                         print(
>                             "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
>                         )
>                     else:
>                         print("\nAppointment Slip Download Failed...")
> 
>                 except Exception as e:
>                     print(str(e))
>                     print("\n\n")
> ```
> 

This doesn't work
![image](https://user-images.githubusercontent.com/24492930/120904702-2f29c900-c66b-11eb-8009-22c8c791435b.png)

2021-06-05 20:35 UTC, dhhruv commented
> > ```
> > try:
> >                     appSlipBase = (
> >                         APPOINTMENT_SLIP_URL
> >                         + f"?appointment_id={resp.json()['appointment_confirmation_no']}"
> >                     )
> >                     appslip = requests.get(appSlipBase, headers=request_header)
> >                     with open(
> >                         f"{resp.json()['appointment_confirmation_no']}.pdf", "wb"
> >                     ) as appSlipPdf:
> >                         appSlipPdf.write(appslip.content)
> >                     if os.path.exists(
> >                         f"{resp.json()['appointment_confirmation_no']}.pdf"
> >                     ):
> >                         print(
> >                             "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> >                         )
> >                     else:
> >                         print("\nAppointment Slip Download Failed...")
> > 
> >                 except Exception as e:
> >                     print(str(e))
> >                     print("\n\n")
> > ```
> > 
> 
> This is same as before right?
> 
> > **OR**
> > 
> > ```
> > try:
> >                     appSlipBase = (
> >                         APPOINTMENT_SLIP_URL
> >                         + f"?appointment_id={resp.json()['appointment_id']}"
> >                     )
> >                     appslip = requests.get(appSlipBase, headers=request_header)
> >                     with open(
> >                         f"{resp.json()['appointment_id']}.pdf", "wb"
> >                     ) as appSlipPdf:
> >                         appSlipPdf.write(appslip.content)
> >                     if os.path.exists(
> >                         f"{resp.json()['appointment_id']}.pdf"
> >                     ):
> >                         print(
> >                             "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> >                         )
> >                     else:
> >                         print("\nAppointment Slip Download Failed...")
> > 
> >                 except Exception as e:
> >                     print(str(e))
> >                     print("\n\n")
> > ```
> > 
> 
> This doesn't work
> ![image](https://user-images.githubusercontent.com/24492930/120904702-2f29c900-c66b-11eb-8009-22c8c791435b.png)
> 
> 

No, the first one is not the same. The symbol in URL `?` got misplaced by `&`. I've solved it and as you've shown the second one is not working then the first snippet will work. There is a change so please reflect in in your local repo.

2021-06-05 20:38 UTC, dhhruv commented
@Nakul93 Let me know the output when done.

2021-06-05 20:40 UTC, Nakul93 commented
Ok now it works. Thanks @dhhruv

2021-06-05 20:43 UTC, dhhruv commented
Sure. Will change it afterwards.

2021-06-06 03:59 UTC, dhhruv commented
Please check #477 for the same.

2021-06-06 03:59 UTC, closed without merging