Appointment Slip Download + Code Re-structured
bombardier-gif/covid-vaccine-booking pull request #477
Opened 2021-06-06 03:58 UTC by dhhruv

- I've added the Functionality of Downloading Appointment Slip as mentioned in #385 .
- Originally Added in #472 but the code had to be changed.
- Re-structued Python code for better visibility and understanding.

2021-06-06 05:43 UTC, Nakul93 commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
Could you please change the name of the file to be mobile_no.pdf, it will be more convenient to identify the file especially when slots are booked for different accounts

2021-06-06 05:51 UTC, 6mxo89sqh commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
Instead I suggest using replacing `.json` to `.pdf` to the config file variable. For docker setup, it will be writeable and available. Saving in Workdir is ephemeral in docker.

2021-06-06 06:00 UTC, dhhruv commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> Could you please change the name of the file to be mobile_no.pdf, it will be more convenient to identify the file especially when slots are booked for different accounts

Changes made as you suggested.

2021-06-06 06:04 UTC, dhhruv commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> Could you please change the name of the file to be mobile_no.pdf, it will be more convenient to identify the file especially when slots are booked for different accounts

@Nakul93 `mobile_appointment` is more preferable because if two appointments have been made using the same number then the previous file will be overwritten.

2021-06-06 06:20 UTC, Nakul93 commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
Not really, if the appointments are made together(for same day and center) then it will club both beneficiaries into 1 pdf, you don't need two separate slips from same account

2021-06-06 06:27 UTC, dhhruv commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> Not really, if the appointments are made together(for same day and center) then it will club both beneficiaries into 1 pdf, you don't need two separate slips from same account

That's not the case. For example, if I have two beneficiaries **(one is in 18+ and another in 45+) OR (Both of them have taken different vaccines)** then I have to do separate booking for both of them. Hence, this name would be preferable as the second booking will overwrite the first pdf if there is only mobile number in pdf.

2021-06-06 06:29 UTC, Nakul93 commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
Yeah true. I was just thinking if there is a better way of naming the file since the appointment no string is too big

2021-06-06 06:43 UTC, dhhruv commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
The Website itself downloads using the same file name. Please let me know if anything comes up.

2021-06-06 06:50 UTC, Nakul93 commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
No it saves in this format : "Appointment_slip.pdf" (just checked)
Maybe you can check if a file of same name exists and if it does then rather than overwriting it you can simply append a number and save it as new file

2021-06-06 08:40 UTC, Nakul93 approved these changes
LGTM

2021-06-06 10:32 UTC, dhhruv commented on src/utils.py
> +                            "\nDownload Successful. Check the Current Working Directory for the Appointment Slip."
> Instead I suggest using replacing `.json` to `.pdf` to the config file variable. For docker setup, it will be writeable and available. Saving in Workdir is ephemeral in docker.

Can you elaborate ? Couldn't understand.

2021-06-06 12:42 UTC, 6mxo89sqh requested changes

2021-06-06 12:42 UTC, 6mxo89sqh commented on src/utils.py
> +                    if os.path.exists(
Hi, for docker env, this path will exist but will not be writable and will through an error. Two options: 1. Don't write it if the path is not writable 2. or write near the config location as that is writable.

2021-06-06 12:50 UTC, dhhruv commented on src/utils.py
> +                    if os.path.exists(
I'm using the cli version from first and haven't gone through docker till now. So is there a way you can elaborate this so I can understand the slow or assign someone else?

2021-06-06 12:57 UTC, 6mxo89sqh commented on src/utils.py
> +                    if os.path.exists(
In docker env, the current working dir may not writable. You may get an error if you attempt to write. So, there are two options, before you write check if it is writable or use the config location (where json is being stored) to store this file.

2021-06-06 17:05 UTC, dhhruv commented on src/utils.py
> +                    if os.path.exists(
Can't we explicitly allow to write using chmod ? Everyone uses the script from the root of this repository as that's convinient.

2021-06-07 12:46 UTC, Nakul93 commented on src/utils.py
> +                    if os.path.exists(
@6mxo89sqh could you guide him here

2021-06-07 12:47 UTC, Nakul93 commented
@dhhruv please resolve the conflicts

2021-06-07 14:24 UTC, 6mxo89sqh commented on src/utils.py
> +                    if os.path.exists(
config file is default your working directory. In docker env, user has to explicitly pass it to enable saving. If you use config_file variable, it should work for both. 

can u resolve the conflicts? i ll approve it. i ll resolve this issue later if someone asks for it.

2021-06-07 17:09 UTC, dhhruv commented on src/utils.py
> +                    if os.path.exists(
> config file is default your working directory. In docker env, user has to explicitly pass it to enable saving. If you use config_file variable, it should work for both.
> 
> can u resolve the conflicts? i ll approve it. i ll resolve this issue later if someone asks for it.

TBH I don't know much about docker so it'd be better if you assign it to someone else.
Sure, I'll resolve.

2021-06-07 17:19 UTC, dhhruv commented
> @dhhruv please resolve the conflicts

Done @Nakul93 @6mxo89sqh . Please do a final check and respond if anything comes up.

2021-06-07 17:38 UTC, Nakul93 commented
All good. Could you also mention about this new feature in readme.

2021-06-08 03:14 UTC, dhhruv commented
> All good. Could you also mention about this new feature in readme.

I'm adding this feature in the Steps, is it ok? Or do you want me to add this somewhere else?

2021-06-08 03:33 UTC, Nakul93 commented
> > All good. Could you also mention about this new feature in readme.
> 
> I'm adding this feature in the Steps, is it ok? Or do you want me to add this somewhere else?

Yeah that should be fine, thanks.

2021-06-08 13:41 UTC, dhhruv commented
> > > All good. Could you also mention about this new feature in readme.
> > 
> > 
> > I'm adding this feature in the Steps, is it ok? Or do you want me to add this somewhere else?
> 
> Yeah that should be fine, thanks.

I've added. Please check @Nakul93 .

2021-06-08 13:45 UTC, merged